### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'sqlparse' distribution was not found and is required by django

### ISSUE THREAD

**Issue by Ashjoker24** [faudeltn/AnsibleTower-awx#1]
Hi I tried your Ansible-AWX installation steps but i getting error on migrating DB in AWX and the error shows like,

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/__init__.py", line 4, in <module>
    __version__ = pkg_resources.require("django-oauth-toolkit")[0].version
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse' distribution was not found and is required by django

**Comment by faudeltn** [comment]
try to run this command: 
sudo pip install -U djangorestframework

**Comment by chandrashekar-cohesity** [comment]
I am facing the same issue. @faudeltn  what you suggest did not fix it.

**Comment by cddisk2000** [comment]
use this command find error

sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"

===========================================
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 136, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 103, in prepare_env
    import oauth2_provider.settings
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/__init__.py", line 4, in <module>
    __version__ = pkg_resources.require("django-oauth-toolkit")[0].version
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse>=0.2.2' distribution was not found and is required by django

===========================================
I am facing the same issue ... how can i do ...

**Comment by greeksachdeva** [comment]
> try to run this command:
> sudo pip install -U djangorestframework

Thanks it worked
